spring.application.name=ebank-bot
server.port=8083

# Configuration de la clé API (référence la variable d'environnement)
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-20b

spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false

spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8081/mcp
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8082/mcp

# discord.token=
telegram.token=7996325911:AAGVIS-ZeHyloASVAtnfoQ9y5TJj6UHALxY
eureka.client.jersey.enabled=false
